# Project Euler | Problem 12 | Jacob Waters
# The sequence of triangle numbers is generated by adding the natural numbers.
# What is the value of the first triangle number to have over five hundred factors?
# 76576500
# date : 2015.01.19

def triangleNumberFactors():
  # Problem 12
  # 76576500 w/ 576 factors
  i = 1
  triangleNumber = 1
  numFactors = 0

  while numFactors < 500:
    # increment triangleNumber
    i += 1
    triangleNumber = triangleNumber + i
    
    # find factors
    factors = [1,triangleNumber]
    for j in xrange(2,int(triangleNumber**0.5)+1):
      if triangleNumber % j == 0:
        if j != triangleNumber/j:
          factors.append(triangleNumber/j)
          factors.append(j)
        else:
          factors.append(j)
    
    # check size
    numFactors = len(factors)
    if numFactors > 500:
      return triangleNumber

print triangleNumberFactors()